import Head from 'next/head';
import React from 'react';
import styles from '../styles/Home.module.css';
import MyNavbar from '../components/MyNavbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MyNavbar />
        <div>
          <div className={styles.displayMiddle}>
            <h1>COMING SOON</h1>
            <p>My Personal Blogpost</p>
          </div>
          <div className={styles.bottomLeft}>
            Powered by{' '}
            <a href="https://nextjs.org/" target="_blank" rel="noreferrer">
              NEXT
            </a>
          </div>
        </div>
      </main>
    </>
  );
}
